services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - appdata:/app/data
      - uploads:/app/uploads
    depends_on:
      - db
    ports:
      - "8000:8000"

  web:
    image: node:20-alpine
    working_dir: /web
    volumes:
      - ./frontend:/web
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000

volumes:
  pgdata:
  appdata:
  uploads:
